export enum TagType {
  MODES_NEVER_HAVE = 'MODES_NEVER_HAVE',
  MODES_PREFER = 'MODES_PREFER',
  MODES_TRUTH_DARE = 'MODES_TRUTH_DARE',
  QUESTIONS_NEVER_HAVE = 'QUESTIONS_NEVER_HAVE',
  QUESTIONS_PREFER = 'QUESTIONS_PREFER',
  QUESTIONS_TRUTH_DARE = 'QUESTIONS_TRUTH_DARE',
  ADMIN_USERS = 'ADMIN_USERS',
  REPORTS = 'REPORTS',
}